/*
* generated by Xtext
*/
package mop.example.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ExpAutoInstUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return mop.example.xtext.ui.internal.ExpAutoInstActivator.getInstance().getInjector("mop.example.xtext.ExpAutoInst");
	}
	
}
