/*
* generated by Xtext
*/
package mop.example.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ExpAutoInstAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("mop/example/xtext/parser/antlr/internal/InternalExpAutoInst.tokens");
	}
}
