/*
 * generated by Xtext
 */
package mop.example.xtext;

import mop.emf.annotations.Libraries;
import mop.emf.core.EMOP;
import mop.emf.core.api.EMOPModelLoad;
import mop.emf.libraries.autoinst.AutoInst2Library;
import mop.emf.libraries.autoinst.AutoInstLibrary;
import exp_autoinst.Exp_autoinstPackage;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpAutoInstRuntimeModule extends mop.example.xtext.AbstractExpAutoInstRuntimeModule {

	static {
		Libraries.install(new AutoInstLibrary("exp_autoinst"));
		EMOPModelLoad.notifyAfter(Exp_autoinstPackage.eINSTANCE.eResource());
		
		// Which is the right place to activate in Xtext?
		EMOP.activate();
	}
	

}
