/*
 * generated by Xtext
 */
package mop.example.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import mop.example.xtext.ui.internal.ExpAutoInstActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExpAutoInstExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExpAutoInstActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExpAutoInstActivator.getInstance().getInjector(ExpAutoInstActivator.MOP_EXAMPLE_XTEXT_EXPAUTOINST);
	}
	
}
