/*
 * generated by Xtext
 */
package mop.example.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExpAutoInstUiModule extends mop.example.xtext.ui.AbstractExpAutoInstUiModule {
	public ExpAutoInstUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
