/**
 * generated by Xtext
 */
package mop.example.xtext.validation;

import mop.example.xtext.validation.AbstractExpAutoInstValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ExpAutoInstValidator extends AbstractExpAutoInstValidator {
}
