/*
 * generated by Xtext
 */
package mop.example.xtext.ui.contentassist

import mop.example.xtext.ui.contentassist.AbstractExpAutoInstProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ExpAutoInstProposalProvider extends AbstractExpAutoInstProposalProvider {
}
